'use client';

import { useEffect, useState, useMemo } from 'react';
import { createClient } from '@/lib/supabase/client';
import type { Product, CartItem, PaymentMethodType } from '@/lib/types';
import ReceiptModal from '@/components/pos/ReceiptModal';
import BarcodeScannerModal from '@/components/pos/BarcodeScannerModal';

export default function POSPage() {
  const supabase = createClient();

  const [search, setSearch] = useState('');
  const [products, setProducts] = useState<Product[]>([]);
  const [cart, setCart] = useState<CartItem[]>([]);
  const [discount, setDiscount] = useState(0);
  const [taxPercentage, setTaxPercentage] = useState(0);
  const [customerName, setCustomerName] = useState('');
  const [customerPhone, setCustomerPhone] = useState('');
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethodType>('cash');
  const [cashReceived, setCashReceived] = useState<number>(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [completedSale, setCompletedSale] = useState<any>(null);
  const [showScanner, setShowScanner] = useState(false);

  // Load tax percentage from settings once
  useEffect(() => {
    supabase
      .from('settings')
      .select('tax_percentage')
      .single()
      .then(({ data }) => {
        if (data) setTaxPercentage(data.tax_percentage);
      });
  }, []);

  // Live product search (name, barcode, product_code)
  useEffect(() => {
    if (search.trim().length === 0) {
      setProducts([]);
      return;
    }
    const timeout = setTimeout(async () => {
      const { data } = await supabase
        .from('products')
        .select('*')
        .eq('status', 'active')
        .or(
          `name.ilike.%${search}%,barcode.eq.${search},product_code.ilike.%${search}%`
        )
        .limit(10);
      setProducts(data || []);
    }, 250);
    return () => clearTimeout(timeout);
  }, [search]);

  async function handleBarcodeDetected(code: string) {
    setShowScanner(false);
    const { data: product } = await supabase
      .from('products')
      .select('*')
      .eq('barcode', code)
      .eq('status', 'active')
      .single();

    if (!product) {
      setError(`Produk dengan barcode "${code}" tidak ditemukan.`);
      return;
    }
    addToCart(product);
  }

  function addToCart(product: Product) {
    if (product.stock <= 0) {
      setError(`Stok "${product.name}" habis.`);
      return;
    }
    setError(null);
    setCart((prev) => {
      const existing = prev.find((i) => i.product_id === product.id);
      if (existing) {
        if (existing.qty + 1 > product.stock) {
          setError(`Stok "${product.name}" tidak cukup (tersisa ${product.stock}).`);
          return prev;
        }
        return prev.map((i) =>
          i.product_id === product.id ? { ...i, qty: i.qty + 1 } : i
        );
      }
      return [
        ...prev,
        {
          product_id: product.id,
          product_name: product.name,
          price: product.selling_price,
          qty: 1,
          available_stock: product.stock,
        },
      ];
    });
    setSearch('');
    setProducts([]);
  }

  function updateQty(productId: string, delta: number) {
    setCart((prev) =>
      prev
        .map((i) => {
          if (i.product_id !== productId) return i;
          const newQty = i.qty + delta;
          if (newQty > i.available_stock) {
            setError(`Stok "${i.product_name}" tidak cukup (tersisa ${i.available_stock}).`);
            return i;
          }
          return { ...i, qty: newQty };
        })
        .filter((i) => i.qty > 0)
    );
  }

  function removeItem(productId: string) {
    setCart((prev) => prev.filter((i) => i.product_id !== productId));
  }

  const subtotal = useMemo(
    () => cart.reduce((sum, i) => sum + i.price * i.qty, 0),
    [cart]
  );
  const taxAmount = useMemo(
    () => Math.round(((subtotal - discount) * taxPercentage) / 100),
    [subtotal, discount, taxPercentage]
  );
  const grandTotal = Math.max(0, subtotal - discount + taxAmount);
  const changeAmount =
    paymentMethod === 'cash' ? Math.max(0, cashReceived - grandTotal) : 0;

  async function completeTransaction() {
    if (cart.length === 0) {
      setError('Keranjang masih kosong.');
      return;
    }
    if (paymentMethod === 'cash' && cashReceived < grandTotal) {
      setError('Uang yang diterima kurang dari total belanja.');
      return;
    }

    setLoading(true);
    setError(null);

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      setError('Sesi login berakhir, silakan login ulang.');
      setLoading(false);
      return;
    }

    // 1. Insert sale (invoice_number auto-generated by DB trigger)
    const { data: sale, error: saleError } = await supabase
      .from('sales')
      .insert({
        cashier_id: user.id,
        customer_name: customerName || null,
        customer_phone: customerPhone || null,
        subtotal,
        discount,
        tax: taxAmount,
        grand_total: grandTotal,
        payment_method: paymentMethod,
        payment_status: 'paid',
        cash_received: paymentMethod === 'cash' ? cashReceived : null,
        change_amount: paymentMethod === 'cash' ? changeAmount : null,
      })
      .select()
      .single();

    if (saleError || !sale) {
      setError('Gagal menyimpan transaksi: ' + saleError?.message);
      setLoading(false);
      return;
    }

    // 2. Insert sale_items (DB trigger auto-reduces stock + logs it,
    //    and will throw if stock is insufficient — so we check the result)
    const itemsPayload = cart.map((i) => ({
      sale_id: sale.id,
      product_id: i.product_id,
      product_name: i.product_name,
      qty: i.qty,
      price: i.price,
      subtotal: i.price * i.qty,
    }));

    const { error: itemsError } = await supabase.from('sale_items').insert(itemsPayload);

    if (itemsError) {
      // Stock trigger rejected it (e.g. race condition on stock) — the sale
      // row still exists but with no items; mark it cancelled for cleanliness.
      await supabase
        .from('sales')
        .update({ payment_status: 'cancelled' })
        .eq('id', sale.id);
      setError('Transaksi gagal: ' + itemsError.message);
      setLoading(false);
      return;
    }

    setCompletedSale({ ...sale, items: cart });
    setCart([]);
    setDiscount(0);
    setCustomerName('');
    setCustomerPhone('');
    setCashReceived(0);
    setLoading(false);
  }

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-4 md:p-6">
      <div className="grid md:grid-cols-3 gap-4">
        {/* LEFT: Search + Cart */}
        <div className="md:col-span-2 space-y-4">
          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm p-4">
            <div className="flex gap-2">
              <input
                autoFocus
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Cari produk / scan barcode (USB/Bluetooth scanner otomatis terbaca di sini)..."
                className="flex-1 rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              <button
                type="button"
                onClick={() => setShowScanner(true)}
                className="rounded-lg bg-blue-600 hover:bg-blue-700 text-white px-4 text-sm font-medium whitespace-nowrap"
              >
                📷 Scan
              </button>
            </div>
            {products.length > 0 && (
              <div className="mt-2 divide-y divide-slate-100 dark:divide-slate-800 border border-slate-100 dark:border-slate-800 rounded-lg overflow-hidden">
                {products.map((p) => (
                  <button
                    key={p.id}
                    onClick={() => addToCart(p)}
                    className="w-full flex justify-between items-center px-4 py-2.5 text-left hover:bg-blue-50 dark:hover:bg-slate-800 text-sm"
                  >
                    <div>
                      <p className="font-medium">{p.name}</p>
                      <p className="text-xs text-slate-500">
                        {p.barcode} · Stok: {p.stock}
                      </p>
                    </div>
                    <span className="font-semibold text-blue-700 dark:text-blue-400">
                      Rp {p.selling_price.toLocaleString('id-ID')}
                    </span>
                  </button>
                ))}
              </div>
            )}
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm p-4">
            <h2 className="font-semibold mb-3">Keranjang</h2>
            {cart.length === 0 ? (
              <p className="text-sm text-slate-400 text-center py-8">
                Belum ada produk di keranjang.
              </p>
            ) : (
              <div className="space-y-2">
                {cart.map((item) => (
                  <div
                    key={item.product_id}
                    className="flex items-center justify-between gap-3 py-2 border-b border-slate-100 dark:border-slate-800 last:border-0"
                  >
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{item.product_name}</p>
                      <p className="text-xs text-slate-500">
                        Rp {item.price.toLocaleString('id-ID')} / pcs
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => updateQty(item.product_id, -1)}
                        className="w-7 h-7 rounded-full bg-slate-100 dark:bg-slate-800 text-sm font-bold"
                      >
                        −
                      </button>
                      <span className="w-6 text-center text-sm">{item.qty}</span>
                      <button
                        onClick={() => updateQty(item.product_id, 1)}
                        className="w-7 h-7 rounded-full bg-slate-100 dark:bg-slate-800 text-sm font-bold"
                      >
                        +
                      </button>
                    </div>
                    <p className="w-24 text-right text-sm font-semibold">
                      Rp {(item.price * item.qty).toLocaleString('id-ID')}
                    </p>
                    <button
                      onClick={() => removeItem(item.product_id)}
                      className="text-red-500 text-xs font-medium"
                    >
                      Hapus
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* RIGHT: Summary + Payment */}
        <div className="space-y-4">
          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm p-4 space-y-3">
            <input
              value={customerName}
              onChange={(e) => setCustomerName(e.target.value)}
              placeholder="Nama pelanggan (opsional)"
              className="w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm"
            />
            <input
              value={customerPhone}
              onChange={(e) => setCustomerPhone(e.target.value)}
              placeholder="No. WhatsApp pelanggan (opsional)"
              className="w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm"
            />
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm p-4 space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-slate-500">Subtotal</span>
              <span>Rp {subtotal.toLocaleString('id-ID')}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-500">Diskon</span>
              <input
                type="number"
                min={0}
                value={discount}
                onChange={(e) => setDiscount(Number(e.target.value) || 0)}
                className="w-28 text-right rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-2 py-1"
              />
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">Pajak ({taxPercentage}%)</span>
              <span>Rp {taxAmount.toLocaleString('id-ID')}</span>
            </div>
            <div className="flex justify-between text-base font-bold pt-2 border-t border-slate-100 dark:border-slate-800">
              <span>Total</span>
              <span className="text-emerald-600">
                Rp {grandTotal.toLocaleString('id-ID')}
              </span>
            </div>
          </div>

          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm p-4 space-y-3">
            <p className="text-sm font-medium">Metode Pembayaran</p>
            <div className="grid grid-cols-2 gap-2">
              {(['cash', 'qris', 'transfer', 'split'] as PaymentMethodType[]).map((m) => (
                <button
                  key={m}
                  onClick={() => setPaymentMethod(m)}
                  className={`rounded-lg py-2 text-sm font-medium border transition-colors ${
                    paymentMethod === m
                      ? 'bg-blue-600 text-white border-blue-600'
                      : 'border-slate-300 dark:border-slate-700'
                  }`}
                >
                  {m === 'cash' ? 'Tunai' : m === 'qris' ? 'QRIS' : m === 'transfer' ? 'Transfer' : 'Tunai + QRIS'}
                </button>
              ))}
            </div>

            {paymentMethod === 'cash' && (
              <div>
                <label className="text-xs text-slate-500">Uang Diterima</label>
                <input
                  type="number"
                  min={0}
                  value={cashReceived || ''}
                  onChange={(e) => setCashReceived(Number(e.target.value) || 0)}
                  className="w-full rounded-lg border border-slate-300 dark:border-slate-700 bg-transparent px-3 py-2 text-sm mt-1"
                />
                {cashReceived > 0 && (
                  <p className="text-xs text-slate-500 mt-1">
                    Kembalian: Rp {changeAmount.toLocaleString('id-ID')}
                  </p>
                )}
              </div>
            )}
          </div>

          {error && (
            <p className="text-sm text-red-600 bg-red-50 dark:bg-red-950 rounded-lg px-3 py-2">
              {error}
            </p>
          )}

          <button
            onClick={completeTransaction}
            disabled={loading || cart.length === 0}
            className="w-full rounded-lg bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white font-semibold py-3 text-sm"
          >
            {loading ? 'Memproses...' : 'Selesaikan Transaksi'}
          </button>
        </div>
      </div>

      {completedSale && (
        <ReceiptModal sale={completedSale} onClose={() => setCompletedSale(null)} />
      )}

      {showScanner && (
        <BarcodeScannerModal
          onDetected={handleBarcodeDetected}
          onClose={() => setShowScanner(false)}
        />
      )}
    </div>
  );
}
